@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false

'Use Case Diagram 

left to right direction

rectangle "System Actors" as actors {
    
    actor "User" as User
}


rectangle "Use Cases" as usecases{
    usecase "UC6 - Reply directly to a comment in a Discussion" as UC6
    User --> UC6
}


@enduml