@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam actorStyle awesome

title SSD US 013 - To be able to see the discussion's list ordered by date

autonumber

actor "UnregisteredUser" as User
participant ":System" as System

activate User

  User -> System: starts the application
  activate System

    User --> System: requests data (solid line - synchronous)
  deactivate System

  System -> User: Displays homepage (Discussions list sorted by popularity)
  activate System

  User --> System: Requests data organized by date (solid line - synchronous)
deactivate System

  System -> User: Displays homepage (Discussions list sorted by date (newest->oldest))
activate System

@enduml
