@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


title SSD US009: TO FORMAT A DISCUSSION - Alternative One

autonumber

actor "Registred User" as User
participant ":System" as System

activate User

    User -> System : write a text
    activate System

    User -> System : select a format stytle and submit post
    activate System

    System --> User : Displays message of success
    deactivate System

@enduml