@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


title SSD US009: TO FORMAT A DISCUSSION

autonumber

actor "Registred User" as User
participant ":System" as System

activate User

    User -> System : submit a discussion
    activate System

    System --> User : display menu of submission of discussions
    deactivate System

    User -> System : type title and text + change font style
    activate System

    System --> User : Displays message of success
    deactivate System

@enduml