@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title As a user, I want to access the website through a link present in a discussion.

autonumber

actor "User" as Employee
participant ":System" as System

activate Employee

    Employee -> System : Enter email and password
    activate System

        System --> Employee : Check email and password
        'System --> Employee : shows task categories list\n and requests data (reference,\ndescription,\ninformation description,\ntechnical description,\nduration, cost)
    deactivate System

        System --> Employee : Grant user access
    deactivate System

        System --> Employee : Shows discussions that contain a link
    activate System

        System --> Employee : requests data
    deactivate System

    Employee -> System : Click on the link
    activate System

        System --> Employee : Open a new browser tab with the page corresponding to the link.
    deactivate System
@enduml