@startuml Domain Model Diagram

title Domain Model for Hackernews-inspired Forum Web App

class Visitor {
  - visitorID: int
}

class User {
    +userId: String
    +username: String
    +email: String
    +password: String
}

abstract class Post {
  - postID: int
  - title: String
  - timestamp: DateTime
}

class TextPost {
  - content: String
}

class LinkPost {
  - url: String
}

class Comment {
    +commentId: String
    +content: String
    +createdAt: Date
}

class Vote {
    +voteId: String
    +type: VoteType
    +createdAt: Date
}

enum VoteType {
    UPVOTE
    DOWNVOTE
}

User "1" --> "0..*" Post : creates
Visitor "1" -- "0..*" Post : views
Visitor "1" -- "0..*" Comment : lists
Visitor "1" -- "0..*" Vote : sees
Post "1" --> "1" User : belongs to
Post "1" --> "0..*" Comment : has
Comment "1" --> "1" Post : belongs to
Comment "1" --> "1" User : written by
User "1" --> "0..*" Vote : votes
Post "1" --> "0..*" Vote : receives
Post <|-- TextPost
Post <|-- LinkPost

@enduml
