@startuml System Sequence Diagram (SSD)
skinparam monochrome false
skinparam packageStyle rectangle
skinparam shadowing true

title  - US007 - Create a link Post

autonumber

actor "Registered User" as User
participant ":System" as System

activate User

User -> System : Select "Submit"
activate System

System --> User : Display new submission form
deactivate System

User -> System : Enter title, select link and enter link and Click on "Submit post"
activate System

System -> System : Check title and link validity

System -> System : Save post

System --> User : Confirm post submission and return to all discussions
deactivate System
deactivate User

@enduml