@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Registered User" as User
participant ":Posting System" as System

activate User

User -> System : Select "Submit"
activate System

System --> User : Display new submission form
deactivate System

User -> System : Enter title and link
activate System

System --> User : Validate title and link
deactivate System

alt Validation
    System -> System : Check title and link validity

    alt Invalid Title/Link
        System --> User : Display error message (invalid title/link)
    else Valid Title/Link
        System -> System : Save post
        System --> User : Confirm post submission and display post
    end
end

deactivate System
deactivate User

@enduml