@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam style strictuml

title As a user I want to logout 

autonumber

actor "User" as RegisteredUser
participant "System" as System

activate RegisteredUser

RegisteredUser -> System : clicks logout button
activate System

System --> RegisteredUser : displays success message

System -> RegisteredUser : confirms logout and ends session

deactivate System
deactivate RegisteredUser

@enduml


