@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam style strictuml

title US004- Create a discussion

autonumber

actor "User" as Employee
participant "System" as System

activate Employee

Employee -> System : asks to create a new discussion
System --> Employee : requests data (title, text)

Employee -> System : provides requested data (title, text)
Employee -> System : submits discussion
System --> Employee : displays success message

@enduml








