@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam style strictuml

actor "Domain-Driven Designers" as User
participant System as System

User -> System: request to create a new post
activate System
System -> User: opens new window to enter data (title, text)
User -> System: provides requested data (title, text) in new window
User -> System: clicks on submit button in new window
System -> System: validates data
alt Data is valid
    System -> User: displays operation success in new window
    System --> User: closes new window
else Data is invalid
    System -> User: displays operation failure in new window
end

@enduml







