@startuml "Package Diagram"

title "Package Diagram - Grand Vista"
package "src" {

    package "api_test" {}
    
    package "automated-tests" {}

    package "config" {}

    package "modules" {}
        
    package "shared" {}
    
    package "utils" {}
}


@enduml