@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative Two

autonumber

actor "Unregistered User" as User
participant ":Registration System" as System
participant ":Data Base" as Database

activate User

    User -> System : submitRegistration (username, password, email)
    activate System

    alt Valid Credentials

        System --> User : Validate User Credentials (Valid Credentials)
    
        System -> Database: createUserAccount 
    activate Database
    deactivate Database

        System --> User: displayConfirmationMessage()
    
    else Invalid Credentials

        System --> User: Validate User Credentials (Invalid Credentials) 

        System --> User: displayErrorMessage()
    End alt
    
    deactivate System
@enduml