@startuml 
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Unregistered User" as User
participant ":Registration System" as System

activate User

    User -> System : submitRegistration (username, password, email)
    activate System

        System --> User : Validate User Credentials
    
        System --> User : Create User Account (Validate Credentials)
    
        System --> User : Display Confirmation Message (Valid Credentials)
    
        System --> User : Display Error Message (Invalid Credentials)
    
    deactivate System
@enduml