@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title As a registered user I want to comment on a discussion

autonumber

actor "User" as Employee
participant ":System" as System

activate Employee

    Employee -> System : Enter email and password
    activate System 

        System --> Employee : Check email and password
        'System --> Employee : shows task categories list\n and requests data (reference,\ndescription,\ninformation description,\ntechnical description,\nduration, cost)
    deactivate System

        System --> Employee : Grant user access
    deactivate System

     System --> Employee : Show discussions to the user
    deactivate System

    Employee -> System : Click on a discussion
    activate System

        System --> Employee : Show page with discussion and an empty text box
    deactivate System

    Employee -> System : Type in the text box and click Post comment
    activate System

        System --> Employee : Save comment and shows below discussion

    Employee -> System : submits data
    activate System

        System --> Employee : Shows operation success
    deactivate System
@enduml