@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam actorStyle awesome


title SSD US002: TO LOGIN IN SYSTEM - Alternative Three

autonumber

actor "User" as User
participant ":System" as System

activate User

    User -> System : wants to login in system
    activate System

        System --> User : requests data (username + password)
    deactivate System

    User -> System : types incorrect password and submit
    activate System

        System --> User :displays message of insucess
    deactivate System

    User -> System : types correct password and submit
    activate System

        System --> User :displays message of sucess
    deactivate System

@enduml