@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


title SSD US002: TO LOGIN IN SYSTEM - Alternative One

autonumber

actor "Registred User" as User
participant ":System" as System
database ":Database" as Database

activate User

    User -> System : wants to login in system
    activate System

        System --> User : requests data (username, password)
    deactivate System

    User -> System : types correct requested data  (username, password) and submit
    activate System

        System -> Database : Check username and password in DB
    activate System

        Database --> System : validates data
    activate System

        System --> User : Displays message of success
    deactivate System

@enduml