@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



title SSD US002: TO LOGIN IN SYSTEM - Alternative Two

autonumber

actor "Registred User" as User
participant ":System" as System
database ":Database" as Database

activate User

    User -> System : wants to login in system
    activate System

        System --> User : requests data (username + password)
    deactivate System

    User -> System : types incorrect username and submit
    activate System

        System -> Database : verifies data in DB
    activate System

       Database --> System : no match
    activate System

        System --> User :displays message of insucess
    deactivate System



@enduml