@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "User" as User
participant ":System" as System

activate User

    User -> System : want to login in system
    activate System

        System --> User : requests data
    deactivate System

    User -> System : types incorrect requested data (username, password) and submit
    activate System

        System --> User :validates data and displays message of insucess
    deactivate System

@enduml